export const names = [
  "Jonell Fusaro",
  "Pamelia Spooner",
  "Johnetta Fenster",
  "Erinn Gangemi",
  "Lorie Sojka",
  "Alvera Gavin",
  "Gilda Bohon",
  "Dannielle Holmes",
  "Allen Purdie",
  "Bradford Bozek",
  "Soledad Lothrop",
  "Irwin Mefford",
  "Alix Holter",
  "Buffy So",
  "Jeni Gosselin",
  "Sophie Holmen",
  "Jo Donley",
  "Shanel Barreras",
  "Svetlana Vanderwal",
  "Agustina Warwick",
  "Julie Rigo",
  "Shaina Defore",
  "Faustina Brookins",
  "Mimi Twine",
  "January Edmisten",
  "Earlene Neese",
  "Lino Bonney",
  "Jina Mcclay",
  "Alma Way",
  "Arlyne Pelkey",
  "Rosana Lara",
  "Homer Jaeger",
  "Aurora Creager",
  "Beata Dufour",
  "Lucien Rollman",
  "Susanne Andrews",
  "Jc Olivarez",
  "Darlene Goosby",
  "Stan Sapien",
  "Geneva Whitehouse",
  "Liane Edington",
  "Lien Morel",
  "Candra Payson",
  "Jere Salcedo",
  "Krissy Shoup",
  "Yadira Hanselman",
  "Roxann Berlanga",
  "Trevor Smart",
  "Jerrod Tiffany",
  "Jolie Gerken",
  "Maeve Lawson",
  "Joselyn Jenkins",
  "Octavio Weeks",
  "Anya Reyes",
  "Anton Daniels",
  "Maddox Morris",
  "Jerome Cochran",
  "Dakota Wheeler",
  "Makena Cochran",
  "Skylar Orozco",
  "Jay Freeman",
  "Aryana Madden",
  "Raphael Reyes",
  "Alvaro Hawkins",
  "Elvis Obrien",
  "Jayce Barr",
  "Zaria Holmes",
  "Haven Rosario",
  "Nicholas Stokes",
  "Trevor Burns",
  "Ian Bartlett",
  "Nathalia Gill",
  "Celeste Valentine",
  "Nickolas Beard",
  "Jasper Huynh",
  "Rudy Burns",
  "Darius Cole",
  "Mariela Madden",
  "Gavin Deleon",
  "Chace Hensley",
  "Jayden Barrett",
  "Zavier Spence",
  "Madelynn Flores",
  "Daniella Meza",
  "Bailee Bradley",
  "Savanna Blair",
  "Yuliana Charles",
  "Elliott Whitehead",
  "Stephanie Benjamin",
  "Aaden Cole",
  "Layne Jackson",
  "Kayleigh Fry",
  "Gaige Collier",
  "Ashton Lam",
  "Randall Beasley",
  "Audrina Fisher",
  "Alyssa Lawson",
  "Kenzie Allen",
  "Kadyn Cabrera",
  "Bryson Barnett",
  "Patricia Dyer",
  "Charity Norman",
  "Dominik Welch",
  "Carlee Huynh",
  "Sariah Alvarez",
  "Haiden Poole",
  "Lea Nichols",
  "Glenn Flores",
  "Cannon Arnold",
  "Kole Liu",
  "Magdalena Cobb",
  "Kelsie Molina",
  "Moses Acevedo",
  "Allie Castaneda",
  "Alexus Mooney",
  "Nicholas Berger",
  "Chace Hansen",
  "Norah Morton",
  "Melina Fitzpatrick",
  "Beckett Ellison",
  "Mallory Conner",
  "Clare Rich",
  "Avah Ballard",
  "Elise Schwartz",
  "Austin Morales",
  "Allison Shepard",
  "Byron Gallegos",
  "Cason Rivas",
  "Donald Mcdonald",
  "Ellis Arnold",
  "Pierre Ingram",
  "Lacey Pratt",
  "Cherish Leblanc",
  "Kayley Livingston",
  "Triston Boyd",
  "Chace Cooke",
  "Jasiah Braun",
  "Albert Aguirre",
  "Jayden Dixon",
  "Jaden Liu",
  "Marcelo Atkins",
  "Harley Cervantes",
  "Lorelei Donaldson",
  "Zaid Pitts",
  "Quinn Klein",
  "Carter Pope",
  "Bennett Cain",
  "Abbigail Suarez",
  "Melody Frye",
  "Greyson Thompson",
];

export const icons = [
  "android",
  "face",
  "cloud",
  "toys",
  "nature",
  "adb",
  "beach-access",
  "person",
  "casino",
  "ac-unit",
];

export const colors = ["#FF0266", "#03DAC5", "#6200EE", "#FF9900", "#CDDE1F"];
